baseURL = "http://localhost/"
languageCode = "en-us"
title = "Redshift Immersion Day Labs"
theme = "learn"
#sectionPagesMenu = "main"
pygmentsCodeFences = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Concorde Habineza"
description = "Redshift Immersion Day Labs"
ordersectionsby = "weight"
disableSearch = false
disableAssetsBusting = false

disableInlineCopyToClipBoard = true
disableShortcutsTitle = false
disableLanguageSwitchingButton = false
disableBreadcrumb = false
disableNextPrev = false
chapter = true

# For search functionality
[outputs]
home = [ "HTML",  "RSS", "JSON"]
page = [ "HTML"]

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
URL = "s3://<Bucket Name>?region=us-east-2"